# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore Nominatim.API.sln
    - name: Build
      working-directory: src
      run: dotnet build Nominatim.API.sln --no-restore 
    - name: Test
      working-directory: src
      run: dotnet test Nominatim.API.sln --no-build --verbosity normal 
