# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
    inputs:
      has_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: New tool-manifest
      run: dotnet new tool-manifest
    - name: Tool install
      run: dotnet tool install dotnetCampus.TagToVersion
    - name: TagToVersion
      if: ${{ inputs.has_tags }} 
      run: dotnet TagToVersion -t $TAGS -f Version.props
      env:
        TAGS: ${{ inputs.tags }}
    - name: Restore dependencies
      working-directory: src
      run: dotnet restore
    - name: Build
      working-directory: src
      run: dotnet build --no-restore -c release
    - name: Package
      working-directory: src
      run: dotnet pack --no-restore -c release -o ${{env.DOTNET_ROOT}}/app
    # - name: Test
      # working-directory: src
    #   run: dotnet test --no-build --verbosity normal
    - name: Push
      if: ${{ inputs.has_tags }} 
      run: dotnet nuget push ${{env.DOTNET_ROOT}}/app/*.nupkg -k ${{ vars.MYGET_API_KEY }} -s ${{ vars.MYGET_URL }}

